import styled from "styled-components";

// All the below CSS generated by: https://codepo8.github.io/css-fork-on-github-ribbon/

const Banner = styled.span`
  @media screen and (min-width: 800px) {
    position: absolute;
    display: block;
    top: 0;
    right: 0;
    width: 200px;
    overflow: hidden;
    height: 200px;
    z-index: 9999;
  }
`;

const GhLink = styled.a`
  background: #000;
  color: #fff;
  text-decoration: none;
  font-family: arial, sans-serif;
  text-align: center;
  font-weight: bold;
  padding: 5px 40px;
  font-size: 1rem;
  line-height: 2rem;
  position: relative;
  transition: 0.5s;

  :hover {
    background: #c11;
    color: #fff;
  }
  ::before,
  ::after {
    content: "";
    width: 100%;
    display: block;
    position: absolute;
    top: 1px;
    left: 0;
    height: 1px;
    background: #fff;
  }
  ::after {
    bottom: 1px;
    top: auto;
  }

  @media screen and (min-width: 800px) {
    width: 200px;
    position: absolute;
    top: 60px;
    right: -60px;
    transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.8);
  }
`;

export function ForkMeOnGithub() {
  return (
    <Banner>
      <GhLink href="https://github.com/nene/prettier-plugin-sql-cst">
        Fork me on GitHub
      </GhLink>
    </Banner>
  );
}
